// 由 make_study_config.py 自动生成，不要手改；重新运行脚本即可更新。
// 每组是同一模型、同一 prompt_id、同一 seed 下三个提示词版本的视频。
export const config = {
  id: 'geot2v-prompt-pilot-v1-2', version: '1', title: 'GeoT2V 提示词三版对比',
  groups: [
    { id: "cogvideox-5b__S01_orbit_large__seed0", title: "对比组 01 · CogVideoX-5B · S01_orbit_large · seed 0", videos: [
      { id: "cogvideox-5b__S01_orbit_large__seed0-a", src: "videos/cogvideox-5b__S01_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S01_orbit_large__seed0-b", src: "videos/cogvideox-5b__S01_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it.", method: "消融版" },
      { id: "cogvideox-5b__S01_orbit_large__seed0-c", src: "videos/cogvideox-5b__S01_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the blocks, keeping it centered at the same distance and height, until the red arch block on the right side of the stack faces the camera. A stack of colorful wooden geometric blocks on a low table, with a bright red arch block on the right side of the stack and a studio shelf of books and potted plants behind it, in soft, even studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S02_orbit_large__seed0", title: "对比组 02 · CogVideoX-5B · S02_orbit_large · seed 0", videos: [
      { id: "cogvideox-5b__S02_orbit_large__seed0-a", src: "videos/cogvideox-5b__S02_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S02_orbit_large__seed0-b", src: "videos/cogvideox-5b__S02_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-5b__S02_orbit_large__seed0-c", src: "videos/cogvideox-5b__S02_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the pitcher, keeping it centered at the same distance and height, until the pitcher's curved handle faces the camera. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S02_truck_large__seed0", title: "对比组 03 · CogVideoX-5B · S02_truck_large · seed 0", videos: [
      { id: "cogvideox-5b__S02_truck_large__seed0-a", src: "videos/cogvideox-5b__S02_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the pitcher; keep camera orientation and focal length fixed. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S02_truck_large__seed0-b", src: "videos/cogvideox-5b__S02_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the pitcher. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-5b__S02_truck_large__seed0-c", src: "videos/cogvideox-5b__S02_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the pitcher, facing straight ahead, so the pitcher drifts left in the frame with the wall shelf sliding past behind it. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S03_dolly_large__seed0", title: "对比组 04 · CogVideoX-5B · S03_dolly_large · seed 0", videos: [
      { id: "cogvideox-5b__S03_dolly_large__seed0-a", src: "videos/cogvideox-5b__S03_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the island by half of its starting distance; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S03_dolly_large__seed0-b", src: "videos/cogvideox-5b__S03_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the island by half of its starting distance. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-5b__S03_dolly_large__seed0-c", src: "videos/cogvideox-5b__S03_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the kitchen island, travelling halfway to it, so the kitchen island grows much larger in the frame. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S03_truck_large__seed0", title: "对比组 05 · CogVideoX-5B · S03_truck_large · seed 0", videos: [
      { id: "cogvideox-5b__S03_truck_large__seed0-a", src: "videos/cogvideox-5b__S03_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the island; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S03_truck_large__seed0-b", src: "videos/cogvideox-5b__S03_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the island. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-5b__S03_truck_large__seed0-c", src: "videos/cogvideox-5b__S03_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the kitchen island, facing straight ahead, so the kitchen island drifts left in the frame with the row of cabinets sliding past behind it. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S04_dolly_large__seed0", title: "对比组 06 · CogVideoX-5B · S04_dolly_large · seed 0", videos: [
      { id: "cogvideox-5b__S04_dolly_large__seed0-a", src: "videos/cogvideox-5b__S04_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the model by half of its starting distance; keep camera orientation and focal length fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S04_dolly_large__seed0-b", src: "videos/cogvideox-5b__S04_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the model by half of its starting distance. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-5b__S04_dolly_large__seed0-c", src: "videos/cogvideox-5b__S04_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the architectural model, travelling halfway to it, so the architectural model grows much larger in the frame. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S04_locked_control_single__seed0", title: "对比组 07 · CogVideoX-5B · S04_locked_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S04_locked_control_single__seed0-a", src: "videos/cogvideox-5b__S04_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S04_locked_control_single__seed0-b", src: "videos/cogvideox-5b__S04_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "消融版" },
      { id: "cogvideox-5b__S04_locked_control_single__seed0-c", src: "videos/cogvideox-5b__S04_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S05_locked_control_single__seed0", title: "对比组 08 · CogVideoX-5B · S05_locked_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S05_locked_control_single__seed0-a", src: "videos/cogvideox-5b__S05_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S05_locked_control_single__seed0-b", src: "videos/cogvideox-5b__S05_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "消融版" },
      { id: "cogvideox-5b__S05_locked_control_single__seed0-c", src: "videos/cogvideox-5b__S05_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A stone sundial in the center of a paved plaza, with a bronze plaque on the right side of its base and low buildings around the plaza behind it, in clear afternoon sunlight.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S01_orbit_large__seed0", title: "对比组 09 · CogVideoX1.5-5B · S01_orbit_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S01_orbit_large__seed0-a", src: "videos/cogvideox-1-5-5b__S01_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S01_orbit_large__seed0-b", src: "videos/cogvideox-1-5-5b__S01_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S01_orbit_large__seed0-c", src: "videos/cogvideox-1-5-5b__S01_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the blocks, keeping it centered at the same distance and height, until the red arch block on the right side of the stack faces the camera. A stack of colorful wooden geometric blocks on a low table, with a bright red arch block on the right side of the stack and a studio shelf of books and potted plants behind it, in soft, even studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S02_truck_large__seed0", title: "对比组 10 · CogVideoX1.5-5B · S02_truck_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S02_truck_large__seed0-a", src: "videos/cogvideox-1-5-5b__S02_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the pitcher; keep camera orientation and focal length fixed. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S02_truck_large__seed0-b", src: "videos/cogvideox-1-5-5b__S02_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the pitcher. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S02_truck_large__seed0-c", src: "videos/cogvideox-1-5-5b__S02_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the pitcher, facing straight ahead, so the pitcher drifts left in the frame with the wall shelf sliding past behind it. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
  ],
};
