// 由 make_study_config.py 自动生成，不要手改；重新运行脚本即可更新。
// 每组是同一模型、同一 prompt_id、同一 seed 下三个提示词版本的视频。
export const config = {
  id: 'geot2v-prompt-pilot-v1-2', version: '7', title: 'GeoT2V 提示词三版对比', title_en: 'GeoT2V three prompt versions',
  groups: [
    { id: "cogvideox-2b__S01_orbit_large__seed0", title: "对比组 01 · CogVideoX-2B · S01_orbit_large · seed 0", videos: [
      { id: "cogvideox-2b__S01_orbit_large__seed0-a", src: "videos/cogvideox-2b__S01_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S01_orbit_large__seed0-b", src: "videos/cogvideox-2b__S01_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it.", method: "消融版" },
      { id: "cogvideox-2b__S01_orbit_large__seed0-c", src: "videos/cogvideox-2b__S01_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the blocks, keeping it centered at the same distance and height, until the red arch block on the right side of the stack faces the camera. A stack of colorful wooden geometric blocks on a low table, with a bright red arch block on the right side of the stack and a studio shelf of books and potted plants behind it, in soft, even studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S02_orbit_large__seed0", title: "对比组 02 · CogVideoX-2B · S02_orbit_large · seed 0", videos: [
      { id: "cogvideox-2b__S02_orbit_large__seed0-a", src: "videos/cogvideox-2b__S02_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S02_orbit_large__seed0-b", src: "videos/cogvideox-2b__S02_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-2b__S02_orbit_large__seed0-c", src: "videos/cogvideox-2b__S02_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the pitcher, keeping it centered at the same distance and height, until the pitcher's curved handle faces the camera. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S02_truck_large__seed0", title: "对比组 03 · CogVideoX-2B · S02_truck_large · seed 0", videos: [
      { id: "cogvideox-2b__S02_truck_large__seed0-a", src: "videos/cogvideox-2b__S02_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the pitcher; keep camera orientation and focal length fixed. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S02_truck_large__seed0-b", src: "videos/cogvideox-2b__S02_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the pitcher. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-2b__S02_truck_large__seed0-c", src: "videos/cogvideox-2b__S02_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the pitcher, facing straight ahead, so the pitcher drifts left in the frame with the wall shelf sliding past behind it. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S03_dolly_large__seed0", title: "对比组 04 · CogVideoX-2B · S03_dolly_large · seed 0", videos: [
      { id: "cogvideox-2b__S03_dolly_large__seed0-a", src: "videos/cogvideox-2b__S03_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the island by half of its starting distance; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S03_dolly_large__seed0-b", src: "videos/cogvideox-2b__S03_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the island by half of its starting distance. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-2b__S03_dolly_large__seed0-c", src: "videos/cogvideox-2b__S03_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the kitchen island, travelling halfway to it, so the kitchen island grows much larger in the frame. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S03_orbit_large__seed0", title: "对比组 05 · CogVideoX-2B · S03_orbit_large · seed 0", videos: [
      { id: "cogvideox-2b__S03_orbit_large__seed0-a", src: "videos/cogvideox-2b__S03_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the island, keeping it centered and maintaining about the same distance and height. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S03_orbit_large__seed0-b", src: "videos/cogvideox-2b__S03_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the island, keeping it centered and maintaining about the same distance and height. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-2b__S03_orbit_large__seed0-c", src: "videos/cogvideox-2b__S03_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the kitchen island, keeping it centered at the same distance and height, until the wooden stool at the island's right end faces the camera. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S03_truck_large__seed0", title: "对比组 06 · CogVideoX-2B · S03_truck_large · seed 0", videos: [
      { id: "cogvideox-2b__S03_truck_large__seed0-a", src: "videos/cogvideox-2b__S03_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the island; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S03_truck_large__seed0-b", src: "videos/cogvideox-2b__S03_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the island. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-2b__S03_truck_large__seed0-c", src: "videos/cogvideox-2b__S03_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the kitchen island, facing straight ahead, so the kitchen island drifts left in the frame with the row of cabinets sliding past behind it. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S04_dolly_large__seed0", title: "对比组 07 · CogVideoX-2B · S04_dolly_large · seed 0", videos: [
      { id: "cogvideox-2b__S04_dolly_large__seed0-a", src: "videos/cogvideox-2b__S04_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the model by half of its starting distance; keep camera orientation and focal length fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S04_dolly_large__seed0-b", src: "videos/cogvideox-2b__S04_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the model by half of its starting distance. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-2b__S04_dolly_large__seed0-c", src: "videos/cogvideox-2b__S04_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the architectural model, travelling halfway to it, so the architectural model grows much larger in the frame. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S04_locked_control_single__seed0", title: "对比组 08 · CogVideoX-2B · S04_locked_control_single · seed 0", videos: [
      { id: "cogvideox-2b__S04_locked_control_single__seed0-a", src: "videos/cogvideox-2b__S04_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S04_locked_control_single__seed0-b", src: "videos/cogvideox-2b__S04_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-2b__S04_locked_control_single__seed0-c", src: "videos/cogvideox-2b__S04_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S04_truck_large__seed0", title: "对比组 09 · CogVideoX-2B · S04_truck_large · seed 0", videos: [
      { id: "cogvideox-2b__S04_truck_large__seed0-a", src: "videos/cogvideox-2b__S04_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the model; keep camera orientation and focal length fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S04_truck_large__seed0-b", src: "videos/cogvideox-2b__S04_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the model. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-2b__S04_truck_large__seed0-c", src: "videos/cogvideox-2b__S04_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the architectural model, facing straight ahead, so the architectural model drifts left in the frame with the gallery columns sliding past behind it. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S05_dolly_large__seed0", title: "对比组 10 · CogVideoX-2B · S05_dolly_large · seed 0", videos: [
      { id: "cogvideox-2b__S05_dolly_large__seed0-a", src: "videos/cogvideox-2b__S05_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the sundial by half of its starting distance; keep camera orientation and focal length fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S05_dolly_large__seed0-b", src: "videos/cogvideox-2b__S05_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the sundial by half of its starting distance. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it.", method: "消融版" },
      { id: "cogvideox-2b__S05_dolly_large__seed0-c", src: "videos/cogvideox-2b__S05_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the sundial, travelling halfway to it, so the sundial grows much larger in the frame. A stone sundial in the center of a paved plaza, with a bronze plaque on the right side of its base and low buildings around the plaza behind it, in clear afternoon sunlight. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S05_locked_control_single__seed0", title: "对比组 11 · CogVideoX-2B · S05_locked_control_single · seed 0", videos: [
      { id: "cogvideox-2b__S05_locked_control_single__seed0-a", src: "videos/cogvideox-2b__S05_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S05_locked_control_single__seed0-b", src: "videos/cogvideox-2b__S05_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it.", method: "消融版" },
      { id: "cogvideox-2b__S05_locked_control_single__seed0-c", src: "videos/cogvideox-2b__S05_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A stone sundial in the center of a paved plaza, with a bronze plaque on the right side of its base and low buildings around the plaza behind it, in clear afternoon sunlight.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S06_locked_control_single__seed0", title: "对比组 12 · CogVideoX-2B · S06_locked_control_single · seed 0", videos: [
      { id: "cogvideox-2b__S06_locked_control_single__seed0-a", src: "videos/cogvideox-2b__S06_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S06_locked_control_single__seed0-b", src: "videos/cogvideox-2b__S06_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it.", method: "消融版" },
      { id: "cogvideox-2b__S06_locked_control_single__seed0-c", src: "videos/cogvideox-2b__S06_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A wooden planter box full of herbs in a brick courtyard, with a metal watering can by its right end and a stone archway behind the courtyard, in soft overcast daylight.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S06_pan_control_single__seed0", title: "对比组 13 · CogVideoX-2B · S06_pan_control_single · seed 0", videos: [
      { id: "cogvideox-2b__S06_pan_control_single__seed0-a", src: "videos/cogvideox-2b__S06_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S06_pan_control_single__seed0-b", src: "videos/cogvideox-2b__S06_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it.", method: "消融版" },
      { id: "cogvideox-2b__S06_pan_control_single__seed0-c", src: "videos/cogvideox-2b__S06_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the planter across the brick wall and stone archway. A wooden planter box full of herbs in a brick courtyard, with a metal watering can by its right end and a stone archway behind the courtyard, in soft overcast daylight. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S07_pan_control_single__seed0", title: "对比组 14 · CogVideoX-2B · S07_pan_control_single · seed 0", videos: [
      { id: "cogvideox-2b__S07_pan_control_single__seed0-a", src: "videos/cogvideox-2b__S07_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A polished chrome vessel on a low plinth, with colored geometric blocks in the studio behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S07_pan_control_single__seed0-b", src: "videos/cogvideox-2b__S07_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A polished chrome vessel on a low plinth, with colored geometric blocks in the studio behind it.", method: "消融版" },
      { id: "cogvideox-2b__S07_pan_control_single__seed0-c", src: "videos/cogvideox-2b__S07_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the chrome vessel across the colored blocks. A polished chrome vessel with a curved spout on its right side, standing on a low plinth, with colored geometric blocks in the studio behind it reflected in its surface, in bright studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-2b__S08_pan_control_single__seed0", title: "对比组 15 · CogVideoX-2B · S08_pan_control_single · seed 0", videos: [
      { id: "cogvideox-2b__S08_pan_control_single__seed0-a", src: "videos/cogvideox-2b__S08_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A clear glass vessel beside a gridded metal stand, with display rails in the gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-2b__S08_pan_control_single__seed0-b", src: "videos/cogvideox-2b__S08_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A clear glass vessel beside a gridded metal stand, with display rails in the gallery behind it.", method: "消融版" },
      { id: "cogvideox-2b__S08_pan_control_single__seed0-c", src: "videos/cogvideox-2b__S08_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the glass vessel across the display rails. A clear glass vessel with a gridded metal stand to its right, and display rails in the gallery behind it, in bright, even gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S01_orbit_large__seed0", title: "对比组 16 · CogVideoX-5B · S01_orbit_large · seed 0", videos: [
      { id: "cogvideox-5b__S01_orbit_large__seed0-a", src: "videos/cogvideox-5b__S01_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S01_orbit_large__seed0-b", src: "videos/cogvideox-5b__S01_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it.", method: "消融版" },
      { id: "cogvideox-5b__S01_orbit_large__seed0-c", src: "videos/cogvideox-5b__S01_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the blocks, keeping it centered at the same distance and height, until the red arch block on the right side of the stack faces the camera. A stack of colorful wooden geometric blocks on a low table, with a bright red arch block on the right side of the stack and a studio shelf of books and potted plants behind it, in soft, even studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S02_orbit_large__seed0", title: "对比组 17 · CogVideoX-5B · S02_orbit_large · seed 0", videos: [
      { id: "cogvideox-5b__S02_orbit_large__seed0-a", src: "videos/cogvideox-5b__S02_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S02_orbit_large__seed0-b", src: "videos/cogvideox-5b__S02_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-5b__S02_orbit_large__seed0-c", src: "videos/cogvideox-5b__S02_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the pitcher, keeping it centered at the same distance and height, until the pitcher's curved handle faces the camera. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S02_truck_large__seed0", title: "对比组 18 · CogVideoX-5B · S02_truck_large · seed 0", videos: [
      { id: "cogvideox-5b__S02_truck_large__seed0-a", src: "videos/cogvideox-5b__S02_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the pitcher; keep camera orientation and focal length fixed. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S02_truck_large__seed0-b", src: "videos/cogvideox-5b__S02_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the pitcher. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-5b__S02_truck_large__seed0-c", src: "videos/cogvideox-5b__S02_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the pitcher, facing straight ahead, so the pitcher drifts left in the frame with the wall shelf sliding past behind it. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S03_dolly_large__seed0", title: "对比组 19 · CogVideoX-5B · S03_dolly_large · seed 0", videos: [
      { id: "cogvideox-5b__S03_dolly_large__seed0-a", src: "videos/cogvideox-5b__S03_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the island by half of its starting distance; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S03_dolly_large__seed0-b", src: "videos/cogvideox-5b__S03_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the island by half of its starting distance. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-5b__S03_dolly_large__seed0-c", src: "videos/cogvideox-5b__S03_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the kitchen island, travelling halfway to it, so the kitchen island grows much larger in the frame. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S03_orbit_large__seed0", title: "对比组 20 · CogVideoX-5B · S03_orbit_large · seed 0", videos: [
      { id: "cogvideox-5b__S03_orbit_large__seed0-a", src: "videos/cogvideox-5b__S03_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the island, keeping it centered and maintaining about the same distance and height. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S03_orbit_large__seed0-b", src: "videos/cogvideox-5b__S03_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the island, keeping it centered and maintaining about the same distance and height. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-5b__S03_orbit_large__seed0-c", src: "videos/cogvideox-5b__S03_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the kitchen island, keeping it centered at the same distance and height, until the wooden stool at the island's right end faces the camera. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S03_truck_large__seed0", title: "对比组 21 · CogVideoX-5B · S03_truck_large · seed 0", videos: [
      { id: "cogvideox-5b__S03_truck_large__seed0-a", src: "videos/cogvideox-5b__S03_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the island; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S03_truck_large__seed0-b", src: "videos/cogvideox-5b__S03_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the island. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-5b__S03_truck_large__seed0-c", src: "videos/cogvideox-5b__S03_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the kitchen island, facing straight ahead, so the kitchen island drifts left in the frame with the row of cabinets sliding past behind it. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S04_dolly_large__seed0", title: "对比组 22 · CogVideoX-5B · S04_dolly_large · seed 0", videos: [
      { id: "cogvideox-5b__S04_dolly_large__seed0-a", src: "videos/cogvideox-5b__S04_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the model by half of its starting distance; keep camera orientation and focal length fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S04_dolly_large__seed0-b", src: "videos/cogvideox-5b__S04_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the model by half of its starting distance. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-5b__S04_dolly_large__seed0-c", src: "videos/cogvideox-5b__S04_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the architectural model, travelling halfway to it, so the architectural model grows much larger in the frame. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S04_locked_control_single__seed0", title: "对比组 23 · CogVideoX-5B · S04_locked_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S04_locked_control_single__seed0-a", src: "videos/cogvideox-5b__S04_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S04_locked_control_single__seed0-b", src: "videos/cogvideox-5b__S04_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-5b__S04_locked_control_single__seed0-c", src: "videos/cogvideox-5b__S04_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S04_truck_large__seed0", title: "对比组 24 · CogVideoX-5B · S04_truck_large · seed 0", videos: [
      { id: "cogvideox-5b__S04_truck_large__seed0-a", src: "videos/cogvideox-5b__S04_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the model; keep camera orientation and focal length fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S04_truck_large__seed0-b", src: "videos/cogvideox-5b__S04_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the model. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-5b__S04_truck_large__seed0-c", src: "videos/cogvideox-5b__S04_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the architectural model, facing straight ahead, so the architectural model drifts left in the frame with the gallery columns sliding past behind it. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S05_dolly_large__seed0", title: "对比组 25 · CogVideoX-5B · S05_dolly_large · seed 0", videos: [
      { id: "cogvideox-5b__S05_dolly_large__seed0-a", src: "videos/cogvideox-5b__S05_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the sundial by half of its starting distance; keep camera orientation and focal length fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S05_dolly_large__seed0-b", src: "videos/cogvideox-5b__S05_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the sundial by half of its starting distance. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it.", method: "消融版" },
      { id: "cogvideox-5b__S05_dolly_large__seed0-c", src: "videos/cogvideox-5b__S05_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the sundial, travelling halfway to it, so the sundial grows much larger in the frame. A stone sundial in the center of a paved plaza, with a bronze plaque on the right side of its base and low buildings around the plaza behind it, in clear afternoon sunlight. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S05_locked_control_single__seed0", title: "对比组 26 · CogVideoX-5B · S05_locked_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S05_locked_control_single__seed0-a", src: "videos/cogvideox-5b__S05_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S05_locked_control_single__seed0-b", src: "videos/cogvideox-5b__S05_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it.", method: "消融版" },
      { id: "cogvideox-5b__S05_locked_control_single__seed0-c", src: "videos/cogvideox-5b__S05_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A stone sundial in the center of a paved plaza, with a bronze plaque on the right side of its base and low buildings around the plaza behind it, in clear afternoon sunlight.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S06_locked_control_single__seed0", title: "对比组 27 · CogVideoX-5B · S06_locked_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S06_locked_control_single__seed0-a", src: "videos/cogvideox-5b__S06_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S06_locked_control_single__seed0-b", src: "videos/cogvideox-5b__S06_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it.", method: "消融版" },
      { id: "cogvideox-5b__S06_locked_control_single__seed0-c", src: "videos/cogvideox-5b__S06_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A wooden planter box full of herbs in a brick courtyard, with a metal watering can by its right end and a stone archway behind the courtyard, in soft overcast daylight.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S06_pan_control_single__seed0", title: "对比组 28 · CogVideoX-5B · S06_pan_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S06_pan_control_single__seed0-a", src: "videos/cogvideox-5b__S06_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S06_pan_control_single__seed0-b", src: "videos/cogvideox-5b__S06_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it.", method: "消融版" },
      { id: "cogvideox-5b__S06_pan_control_single__seed0-c", src: "videos/cogvideox-5b__S06_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the planter across the brick wall and stone archway. A wooden planter box full of herbs in a brick courtyard, with a metal watering can by its right end and a stone archway behind the courtyard, in soft overcast daylight. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S07_pan_control_single__seed0", title: "对比组 29 · CogVideoX-5B · S07_pan_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S07_pan_control_single__seed0-a", src: "videos/cogvideox-5b__S07_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A polished chrome vessel on a low plinth, with colored geometric blocks in the studio behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S07_pan_control_single__seed0-b", src: "videos/cogvideox-5b__S07_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A polished chrome vessel on a low plinth, with colored geometric blocks in the studio behind it.", method: "消融版" },
      { id: "cogvideox-5b__S07_pan_control_single__seed0-c", src: "videos/cogvideox-5b__S07_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the chrome vessel across the colored blocks. A polished chrome vessel with a curved spout on its right side, standing on a low plinth, with colored geometric blocks in the studio behind it reflected in its surface, in bright studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-5b__S08_pan_control_single__seed0", title: "对比组 30 · CogVideoX-5B · S08_pan_control_single · seed 0", videos: [
      { id: "cogvideox-5b__S08_pan_control_single__seed0-a", src: "videos/cogvideox-5b__S08_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A clear glass vessel beside a gridded metal stand, with display rails in the gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-5b__S08_pan_control_single__seed0-b", src: "videos/cogvideox-5b__S08_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A clear glass vessel beside a gridded metal stand, with display rails in the gallery behind it.", method: "消融版" },
      { id: "cogvideox-5b__S08_pan_control_single__seed0-c", src: "videos/cogvideox-5b__S08_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the glass vessel across the display rails. A clear glass vessel with a gridded metal stand to its right, and display rails in the gallery behind it, in bright, even gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S01_orbit_large__seed0", title: "对比组 31 · CogVideoX1.5-5B · S01_orbit_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S01_orbit_large__seed0-a", src: "videos/cogvideox-1-5-5b__S01_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S01_orbit_large__seed0-b", src: "videos/cogvideox-1-5-5b__S01_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the blocks, keeping it centered and maintaining about the same distance and height. A stack of colorful wooden geometric blocks on a low table, with a studio shelf behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S01_orbit_large__seed0-c", src: "videos/cogvideox-1-5-5b__S01_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the blocks, keeping it centered at the same distance and height, until the red arch block on the right side of the stack faces the camera. A stack of colorful wooden geometric blocks on a low table, with a bright red arch block on the right side of the stack and a studio shelf of books and potted plants behind it, in soft, even studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S02_orbit_large__seed0", title: "对比组 32 · CogVideoX1.5-5B · S02_orbit_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S02_orbit_large__seed0-a", src: "videos/cogvideox-1-5-5b__S02_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S02_orbit_large__seed0-b", src: "videos/cogvideox-1-5-5b__S02_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the pitcher, keeping it centered and maintaining about the same distance and height. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S02_orbit_large__seed0-c", src: "videos/cogvideox-1-5-5b__S02_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the pitcher, keeping it centered at the same distance and height, until the pitcher's curved handle faces the camera. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S02_truck_large__seed0", title: "对比组 33 · CogVideoX1.5-5B · S02_truck_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S02_truck_large__seed0-a", src: "videos/cogvideox-1-5-5b__S02_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the pitcher; keep camera orientation and focal length fixed. A matte clay pitcher with two cups on a table, with a wall shelf behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S02_truck_large__seed0-b", src: "videos/cogvideox-1-5-5b__S02_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the pitcher. A matte clay pitcher with two cups on a table, with a wall shelf behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S02_truck_large__seed0-c", src: "videos/cogvideox-1-5-5b__S02_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the pitcher, facing straight ahead, so the pitcher drifts left in the frame with the wall shelf sliding past behind it. A matte clay pitcher with two cups on a wooden table, the pitcher's curved handle on its right side, and a wall shelf with jars behind it, in soft daylight from a window. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S03_dolly_large__seed0", title: "对比组 34 · CogVideoX1.5-5B · S03_dolly_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S03_dolly_large__seed0-a", src: "videos/cogvideox-1-5-5b__S03_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the island by half of its starting distance; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S03_dolly_large__seed0-b", src: "videos/cogvideox-1-5-5b__S03_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the island by half of its starting distance. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S03_dolly_large__seed0-c", src: "videos/cogvideox-1-5-5b__S03_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the kitchen island, travelling halfway to it, so the kitchen island grows much larger in the frame. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S03_orbit_large__seed0", title: "对比组 35 · CogVideoX1.5-5B · S03_orbit_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S03_orbit_large__seed0-a", src: "videos/cogvideox-1-5-5b__S03_orbit_large__seed0__a.mp4", prompt: "Orbit 90 degrees clockwise around the island, keeping it centered and maintaining about the same distance and height. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S03_orbit_large__seed0-b", src: "videos/cogvideox-1-5-5b__S03_orbit_large__seed0__b.mp4", prompt: "Orbit 90 degrees clockwise around the island, keeping it centered and maintaining about the same distance and height. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S03_orbit_large__seed0-c", src: "videos/cogvideox-1-5-5b__S03_orbit_large__seed0__c.mp4", prompt: "The camera smoothly orbits a quarter circle, 90 degrees, to the right around the kitchen island, keeping it centered at the same distance and height, until the wooden stool at the island's right end faces the camera. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S03_truck_large__seed0", title: "对比组 36 · CogVideoX1.5-5B · S03_truck_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S03_truck_large__seed0-a", src: "videos/cogvideox-1-5-5b__S03_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the island; keep camera orientation and focal length fixed. A small kitchen island with a wooden stool, with cabinets along the back wall behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S03_truck_large__seed0-b", src: "videos/cogvideox-1-5-5b__S03_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the island. A small kitchen island with a wooden stool, with cabinets along the back wall behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S03_truck_large__seed0-c", src: "videos/cogvideox-1-5-5b__S03_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the kitchen island, facing straight ahead, so the kitchen island drifts left in the frame with the row of cabinets sliding past behind it. A small kitchen island with a butcher-block top, a wooden stool tucked against its right end, and cabinets along the back wall behind it, in warm, even interior light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S04_dolly_large__seed0", title: "对比组 37 · CogVideoX1.5-5B · S04_dolly_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S04_dolly_large__seed0-a", src: "videos/cogvideox-1-5-5b__S04_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the model by half of its starting distance; keep camera orientation and focal length fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S04_dolly_large__seed0-b", src: "videos/cogvideox-1-5-5b__S04_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the model by half of its starting distance. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S04_dolly_large__seed0-c", src: "videos/cogvideox-1-5-5b__S04_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the architectural model, travelling halfway to it, so the architectural model grows much larger in the frame. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S04_locked_control_single__seed0", title: "对比组 38 · CogVideoX1.5-5B · S04_locked_control_single · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S04_locked_control_single__seed0-a", src: "videos/cogvideox-1-5-5b__S04_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S04_locked_control_single__seed0-b", src: "videos/cogvideox-1-5-5b__S04_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S04_locked_control_single__seed0-c", src: "videos/cogvideox-1-5-5b__S04_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S04_truck_large__seed0", title: "对比组 39 · CogVideoX1.5-5B · S04_truck_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S04_truck_large__seed0-a", src: "videos/cogvideox-1-5-5b__S04_truck_large__seed0__a.mp4", prompt: "Translate the camera to the right by one width of the model; keep camera orientation and focal length fixed. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S04_truck_large__seed0-b", src: "videos/cogvideox-1-5-5b__S04_truck_large__seed0__b.mp4", prompt: "Translate the camera to the right by one width of the model. A wooden plinth holding a detailed architectural model, with columns across the empty gallery behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S04_truck_large__seed0-c", src: "videos/cogvideox-1-5-5b__S04_truck_large__seed0__c.mp4", prompt: "Tracking shot: the camera glides sideways to the right by about the full width of the architectural model, facing straight ahead, so the architectural model drifts left in the frame with the gallery columns sliding past behind it. A wooden plinth holding a detailed architectural model with a small clock tower at its right end, and white columns across an empty gallery behind it, in bright gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S05_dolly_large__seed0", title: "对比组 40 · CogVideoX1.5-5B · S05_dolly_large · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S05_dolly_large__seed0-a", src: "videos/cogvideox-1-5-5b__S05_dolly_large__seed0__a.mp4", prompt: "Move the camera straight toward the sundial by half of its starting distance; keep camera orientation and focal length fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S05_dolly_large__seed0-b", src: "videos/cogvideox-1-5-5b__S05_dolly_large__seed0__b.mp4", prompt: "Move the camera straight toward the sundial by half of its starting distance. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S05_dolly_large__seed0-c", src: "videos/cogvideox-1-5-5b__S05_dolly_large__seed0__c.mp4", prompt: "The camera dollies forward toward the sundial, travelling halfway to it, so the sundial grows much larger in the frame. A stone sundial in the center of a paved plaza, with a bronze plaque on the right side of its base and low buildings around the plaza behind it, in clear afternoon sunlight. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S05_locked_control_single__seed0", title: "对比组 41 · CogVideoX1.5-5B · S05_locked_control_single · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S05_locked_control_single__seed0-a", src: "videos/cogvideox-1-5-5b__S05_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S05_locked_control_single__seed0-b", src: "videos/cogvideox-1-5-5b__S05_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A stone sundial in the center of a paved plaza, with low buildings around the plaza behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S05_locked_control_single__seed0-c", src: "videos/cogvideox-1-5-5b__S05_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A stone sundial in the center of a paved plaza, with a bronze plaque on the right side of its base and low buildings around the plaza behind it, in clear afternoon sunlight.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S06_locked_control_single__seed0", title: "对比组 42 · CogVideoX1.5-5B · S06_locked_control_single · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S06_locked_control_single__seed0-a", src: "videos/cogvideox-1-5-5b__S06_locked_control_single__seed0__a.mp4", prompt: "Keep the camera position and orientation fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S06_locked_control_single__seed0-b", src: "videos/cogvideox-1-5-5b__S06_locked_control_single__seed0__b.mp4", prompt: "Keep the camera position and orientation fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S06_locked_control_single__seed0-c", src: "videos/cogvideox-1-5-5b__S06_locked_control_single__seed0__c.mp4", prompt: "Static shot from a locked-off camera on a tripod; the frame stays completely still. A wooden planter box full of herbs in a brick courtyard, with a metal watering can by its right end and a stone archway behind the courtyard, in soft overcast daylight.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S06_pan_control_single__seed0", title: "对比组 43 · CogVideoX1.5-5B · S06_pan_control_single · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S06_pan_control_single__seed0-a", src: "videos/cogvideox-1-5-5b__S06_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S06_pan_control_single__seed0-b", src: "videos/cogvideox-1-5-5b__S06_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A wooden planter box in a brick courtyard, with a stone archway behind the courtyard behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S06_pan_control_single__seed0-c", src: "videos/cogvideox-1-5-5b__S06_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the planter across the brick wall and stone archway. A wooden planter box full of herbs in a brick courtyard, with a metal watering can by its right end and a stone archway behind the courtyard, in soft overcast daylight. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S07_pan_control_single__seed0", title: "对比组 44 · CogVideoX1.5-5B · S07_pan_control_single · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S07_pan_control_single__seed0-a", src: "videos/cogvideox-1-5-5b__S07_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A polished chrome vessel on a low plinth, with colored geometric blocks in the studio behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S07_pan_control_single__seed0-b", src: "videos/cogvideox-1-5-5b__S07_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A polished chrome vessel on a low plinth, with colored geometric blocks in the studio behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S07_pan_control_single__seed0-c", src: "videos/cogvideox-1-5-5b__S07_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the chrome vessel across the colored blocks. A polished chrome vessel with a curved spout on its right side, standing on a low plinth, with colored geometric blocks in the studio behind it reflected in its surface, in bright studio light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
    { id: "cogvideox-1-5-5b__S08_pan_control_single__seed0", title: "对比组 45 · CogVideoX1.5-5B · S08_pan_control_single · seed 0", videos: [
      { id: "cogvideox-1-5-5b__S08_pan_control_single__seed0-a", src: "videos/cogvideox-1-5-5b__S08_pan_control_single__seed0__a.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis; keep camera position and focal length fixed. A clear glass vessel beside a gridded metal stand, with display rails in the gallery behind it. Objects remain still under steady lighting. Single continuous shot; fixed focal length.", method: "v1.1 原版" },
      { id: "cogvideox-1-5-5b__S08_pan_control_single__seed0-b", src: "videos/cogvideox-1-5-5b__S08_pan_control_single__seed0__b.mp4", prompt: "Rotate right 30 degrees in place around the vertical axis. A clear glass vessel beside a gridded metal stand, with display rails in the gallery behind it.", method: "消融版" },
      { id: "cogvideox-1-5-5b__S08_pan_control_single__seed0-c", src: "videos/cogvideox-1-5-5b__S08_pan_control_single__seed0__c.mp4", prompt: "Tripod pan: the camera turns 30 degrees to the right on its tripod, sweeping the view from the glass vessel across the display rails. A clear glass vessel with a gridded metal stand to its right, and display rails in the gallery behind it, in bright, even gallery light. Smooth, continuous camera movement from the first frame to the last.", method: "v1.2 新版" },
    ] },
  ],
};
